title: Ivalice Alliance
description: A website with news and all things related to the Ivalice Alliance clan.
keyword: ivalice alliance, clan, gaming, final fantasy, xii, xiv
url: https://www.ivalicealliance.net
logo: /assets/images/clanlogo.png
discord: https://discord.gg/TEVk6n5
twitter:
  username: clan_ia
social:
  links:
    - https://twitter.com/clan_ia
github: ivalicealliance
author: 
  name: Balthier
  twitter: balthier_ex
year: 2008
markdown: kramdown
paginate: 5
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
exclude:
  - "node_modules"
  - "scss"
  - "gulpfile.js"
  - "bower.json"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "LICENSE"
  - "Gemfile"
  - "Gemfile.lock"  
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "_posts"
    values:
      layout: default
      post: true