name : Ivalice Alliance
description : Website for Ivalice Alliance
keyword : ivalice, alliance, clan, gaming, final, fantasy, xii
url : https://www.ivalicealliance.net
discord: https://discord.gg/TEVk6n5
twitter : clan_ia
github : ivalicealliance
author : Balthier
year : 2008
markdown : kramdown
paginate: 5
plugins: [jekyll-paginate]
exclude :
  - "node_modules"
  - "scss"
  - "gulpfile.js"
  - "bower.json"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "LICENSE"
  - "Gemfile"
  - "Gemfile.lock"  
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "_posts"
    values:
      layout: default
      post: true